services:
  postgres:
    image: postgres:latest
    container_name: postgresContainer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodbContainer
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  redis:
    image: redis:latest
    container_name: redisContainer
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: [ "server", "/data", "--console-address", ":9001" ]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
