spring:
  application:
    name: evt-core-service

  datasource:
    url: jdbc:postgresql://localhost:5432/evently
    username: ${SPRING_DATASOURCE_USERNAME:evently}
    password: ${SPRING_DATASOURCE_PASSWORD:evently}
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

server:
  port: 8080

grpc:
  server:
    port: 9090